/**
 * Vite plugin that resolves virtual modules for Agent-Tale.
 *
 * Provides:
 *   import { graph, getBacklinks, getRelated, getOrphans } from 'agent-tale:graph';
 *
 * The graph is built once at startup and the virtual module exports
 * a serialized snapshot that Astro components can import at build time.
 */

import type { Graph, GraphNode } from '@agent-tale/core';

const VIRTUAL_MODULE_ID = 'agent-tale:graph';
const RESOLVED_VIRTUAL_ID = '\0' + VIRTUAL_MODULE_ID;

export interface VitePluginOptions {
  graph: Graph;
}

export function agentTaleVitePlugin(options: VitePluginOptions) {
  const { graph } = options;

  return {
    name: 'agent-tale:vite-plugin',
    resolveId(id: string) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_ID;
      }
    },
    load(id: string) {
      if (id === RESOLVED_VIRTUAL_ID) {
        return generateVirtualModule(graph);
      }
    },
  };
}

function generateVirtualModule(graph: Graph): string {
  const stats = graph.getStats();

  // Serialize nodes as a plain array (Maps aren't serializable)
  const nodesArray = Array.from(graph.nodes.values());
  const edgesArray = graph.edges;

  // Pre-compute backlinks for every node so templates don't need to call at runtime
  const backlinksMap: Record<string, Array<{ slug: string; title: string }>> = {};
  for (const node of nodesArray) {
    backlinksMap[node.slug] = graph.getBacklinks(node.slug).map((n) => ({
      slug: n.slug,
      title: n.title,
    }));
  }

  // Pre-compute related posts for every node
  const relatedMap: Record<string, Array<{ slug: string; title: string }>> = {};
  for (const node of nodesArray) {
    relatedMap[node.slug] = graph.getRelated(node.slug).map((n) => ({
      slug: n.slug,
      title: n.title,
    }));
  }

  const orphans = graph.getOrphans().map((n) => ({
    slug: n.slug,
    title: n.title,
  }));

  return `
// Auto-generated by agent-tale:vite-plugin — do not edit
export const nodes = ${JSON.stringify(nodesArray)};
export const edges = ${JSON.stringify(edgesArray)};
export const stats = ${JSON.stringify(stats)};
export const orphans = ${JSON.stringify(orphans)};

const backlinksMap = ${JSON.stringify(backlinksMap)};
const relatedMap = ${JSON.stringify(relatedMap)};

export function getBacklinks(slug) {
  return backlinksMap[slug] ?? [];
}

export function getRelated(slug) {
  return relatedMap[slug] ?? [];
}

export function getNode(slug) {
  return nodes.find(n => n.slug === slug) ?? null;
}

export const graph = { nodes, edges, stats, orphans, getBacklinks, getRelated, getNode };
export default graph;
`;
}
